In [12]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression

In [13]:
df = pd.read_csv('zhengqi_train.txt', sep='\t')
X_train = df.iloc[:, :-1]   # 训练数据
y_train = df[['target']]  # 目标值
y_train

      target
0      0.175
1      0.676
2      0.633
3      0.206
4      0.384
...      ...
2883   0.235
2884   1.042
2885   0.005
2886   0.350
2887   0.417

[2888 rows x 1 columns]

In [14]:
# 测试数据
X_test = pd.read_csv('zhengqi_test.txt', sep='\t')
display(X_train.head(), y_train.head(), X_test.head())

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V28,V29,V30,V31,V32,V33,V34,V35,V36,V37
0,0.566,0.016,-0.143,0.407,0.452,-0.901,-1.812,-2.360,-0.436,-2.114,...,-0.450,0.136,0.109,-0.615,0.327,-4.627,-4.789,-5.101,-2.608,-3.508
1,0.968,0.437,0.066,0.566,0.194,-0.893,-1.566,-2.360,0.332,-2.114,...,0.671,-0.128,0.124,0.032,0.600,-0.843,0.160,0.364,-0.335,-0.730
2,1.013,0.568,0.235,0.370,0.112,-0.797,-1.367,-2.360,0.396,-2.114,...,1.287,-0.009,0.361,0.277,-0.116,-0.843,0.160,0.364,0.765,-0.589
3,0.733,0.368,0.283,0.165,0.599,-0.679,-1.200,-2.086,0.403,-2.114,...,1.298,0.015,0.417,0.279,0.603,-0.843,-0.065,0.364,0.333,-0.112
4,0.684,0.638,0.260,0.209,0.337,-0.454,-1.073,-2.086,0.314,-2.114,...,1.289,0.183,1.078,0.328,0.418,-0.843,-0.215,0.364,-0.280,-0.028

   target
0   0.175
1   0.676
2   0.633
3   0.206
4   0.384

,V0,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V28,V29,V30,V31,V32,V33,V34,V35,V36,V37
0,0.368,0.380,-0.225,-0.049,0.379,0.092,0.550,0.551,0.244,0.904,...,-0.449,0.047,0.057,-0.042,0.847,0.534,-0.009,-0.190,-0.567,0.388
1,0.148,0.489,-0.247,-0.049,0.122,-0.201,0.487,0.493,-0.127,0.904,...,-0.443,0.047,0.560,0.176,0.551,0.046,-0.220,0.008,-0.294,0.104
2,-0.166,-0.062,-0.311,0.046,-0.055,0.063,0.485,0.493,-0.227,0.904,...,-0.458,-0.398,0.101,0.199,0.634,0.017,-0.234,0.008,0.373,0.569
3,0.102,0.294,-0.259,0.051,-0.183,0.148,0.474,0.504,0.010,0.904,...,-0.456,-0.398,1.007,0.137,1.042,-0.040,-0.290,0.008,-0.666,0.391
4,0.300,0.428,0.208,0.051,-0.033,0.116,0.408,0.497,0.155,0.904,...,-0.458,-0.776,0.291,0.370,0.181,-0.040,-0.290,0.008,-0.140,-0.497

### 不使用归一化

In [16]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [17]:
model.predict(X_test)

array([[ 0.26825457],
       [ 0.2600059 ],
       [-0.06905626],
       ...,
       [-3.53171707],
       [-3.48378753],
       [-2.74290238]])

### 使用最大值最小值进行归一化

In [18]:
norm = MinMaxScaler()
X_train_norm = norm.fit_transform(X_train)
y_train_norm = norm.fit_transform(y_train)
X_test_norm = norm.fit_transform(X_test)

In [19]:
model = LinearRegression()
model.fit(X_train_norm, y_train_norm)

LinearRegression()

In [20]:
model.predict(X_test_norm)

array([[0.69801031],
       [0.6861968 ],
       [0.65270343],
       ...,
       [0.26055745],
       [0.24754376],
       [0.37197479]])

### 使用0均值归一化

In [22]:
norm = StandardScaler()
X_train_norm = norm.fit_transform(X_train)
y_train_norm = norm.fit_transform(y_train)
X_test_norm = norm.fit_transform(X_test)

In [23]:
model = LinearRegression()
model.fit(X_train_norm, y_train_norm)

LinearRegression()

In [25]:
model.predict(X_test_norm)[:15]

array([[ 0.52564964],
       [ 0.48973218],
       [ 0.32666665],
       [ 0.36998727],
       [ 0.5268688 ],
       [ 0.46154774],
       [ 0.22804888],
       [ 0.48236749],
       [ 0.21097507],
       [ 0.49360554],
       [-0.10965964],
       [-0.09819487],
       [-0.02267627],
       [ 0.26229629],
       [ 0.24690629]])